In [1]:
import pandas as pd
import numpy as np

In [2]:
names = pd.read_csv('data/names.csv')

In [3]:
names

       Name  Age
0  Cornelia   70
1     Abbas   69
2  Penelope    4
3      Niko    2

In [4]:
new_data_list = ['Aria', 1]

In [5]:
names.loc[4] = new_data_list

In [6]:
names

       Name  Age
0  Cornelia   70
1     Abbas   69
2  Penelope    4
3      Niko    2
4      Aria    1

In [7]:
names.loc['five'] = ['Zach', 3]

In [8]:
names

          Name  Age
0     Cornelia   70
1        Abbas   69
2     Penelope    4
3         Niko    2
4         Aria    1
five      Zach    3

In [9]:
names.loc[len(names)] = {'Name': 'Zayd', 'Age': 2}

In [10]:
names

          Name  Age
0     Cornelia   70
1        Abbas   69
2     Penelope    4
3         Niko    2
4         Aria    1
five      Zach    3
6         Zayd    2

In [11]:
names.loc[len(names)] = pd.Series({'Age': 32, 'Name': 'Dean'})

In [12]:
names

          Name  Age
0     Cornelia   70
1        Abbas   69
2     Penelope    4
3         Niko    2
4         Aria    1
five      Zach    3
6         Zayd    2
7         Dean   32

In [13]:
names = pd.read_csv('data/names.csv')

In [14]:
names.append({'Name': 'Aria', 'Age': 1})

/var/folders/j_/hylrqd052y9czkfmjyyc7n7r0000gn/T/ipykernel_5769/1527977704.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  names.append({'Name': 'Aria', 'Age': 1})

TypeError: Can only append a dict if ignore_index=True

In [18]:
names.append({'Name': 'Aria', 'Age': 1}, ignore_index=True)

/var/folders/j_/hylrqd052y9czkfmjyyc7n7r0000gn/T/ipykernel_5769/1904898704.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  names.append({'Name': 'Aria', 'Age': 1}, ignore_index=True)

       Name  Age
0  Cornelia   70
1     Abbas   69
2  Penelope    4
3      Niko    2
4      Aria    1

In [20]:
names.index = ['Canada', 'Canada', 'USA', 'USA']

In [21]:
names

            Name  Age
Canada  Cornelia   70
Canada     Abbas   69
USA     Penelope    4
USA         Niko    2

In [22]:
s = pd.Series({'Name': 'Zach', 'Age': 3}, name=len(names))
s

Name    Zach
Age        3
Name: 4, dtype: object

In [24]:
names.append(s)

/var/folders/j_/hylrqd052y9czkfmjyyc7n7r0000gn/T/ipykernel_5769/3392881922.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  names.append(s)

            Name  Age
Canada  Cornelia   70
Canada     Abbas   69
USA     Penelope    4
USA         Niko    2
4           Zach    3

In [26]:
s1 = pd.Series({'Name': 'Zach', 'Age': 3}, name=len(names))
s2 = pd.Series({'Name': 'Zayd', 'Age': 2}, name='USA')

In [27]:
names.append([s1, s2])

/var/folders/j_/hylrqd052y9czkfmjyyc7n7r0000gn/T/ipykernel_5769/278860800.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  names.append([s1, s2])

            Name  Age
Canada  Cornelia   70
Canada     Abbas   69
USA     Penelope    4
USA         Niko    2
4           Zach    3
USA         Zayd    2

In [28]:
bball_16 = pd.read_csv('data/baseball16.csv')

In [29]:
bball_16

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,altuvjo01,2016,1,HOU,AL,161,640,108,216,42,...,96.0,30.0,10.0,60,70.0,11.0,7.0,3.0,7.0,15.0
1,bregmal01,2016,1,HOU,AL,49,201,31,53,13,...,34.0,2.0,0.0,15,52.0,0.0,0.0,0.0,1.0,1.0
2,castrja01,2016,1,HOU,AL,113,329,41,69,16,...,32.0,2.0,1.0,45,123.0,0.0,1.0,1.0,0.0,9.0
3,correca01,2016,1,HOU,AL,153,577,76,158,36,...,96.0,13.0,3.0,75,139.0,5.0,5.0,0.0,3.0,12.0
4,gattiev01,2016,1,HOU,AL,128,447,58,112,19,...,72.0,2.0,1.0,43,127.0,6.0,4.0,0.0,5.0,12.0
5,gomezca01,2016,1,HOU,AL,85,295,27,62,16,...,29.0,13.0,2.0,21,100.0,2.0,4.0,3.0,0.0,11.0
6,gonzama01,2016,1,HOU,AL,141,484,55,123,26,...,51.0,12.0,6.0,22,118.0,1.0,5.0,6.0,1.0,16.0
7,gourryu01,2016,1,HOU,AL,36,130,13,34,7,...,15.0,1.0,1.0,5,12.0,0.0,1.0,0.0,1.0,7.0
8,kempto01,2016,1,HOU,AL,59,120,15,26,4,...,7.0,2.0,1.0,14,27.0,0.0,0.0,1.0,1.0,5.0
9,marisja01,2016,1,HOU,AL,118,287,40,60,18,...,21.0,10.0,5.0,16,83.0,0.0,3.0,4.0,1.0,4.0
10,rasmuco01,2016,1,HOU,AL,107,369,38,76,10,...,54.0,4.0,1.0,43,121.0,0.0,0.0,1.0,4.0,5.0
11,reedaj01,2016,1,HOU,AL,45,122,11,20,3,...,8.0,0.0,0.0,18,48.0,0.0,0.0,0.0,1.0,1.0
12,springe01,2016,1,HOU,AL,162,644,116,168,29,...,82.0,9.0,10.0,88,178.0,2.0,11.0,0.0,1.0,12.0
13,tuckepr01,2016,1,HOU,AL,48,134,11,22,8,...,8.0,0.0,0.0,8,40.0,0.0,2.0,0.0,0.0,2.0
14,valbulu01,2016,1,HOU,AL,90,292,38,76,17,...,40.0,1.0,1.0,44,81.0,2.0,1.0,3.0,2.0,5.0
15,whitety01,2016,1,HOU,AL,86,249,24,54,16,...,28.0,1.0,0.0,23,65.0,1.0,2.0,0.0,2.0,6.0

In [30]:
data_dict = bball_16.iloc[0].to_dict()

In [31]:
data_dict

{'playerID': 'altuvjo01',
 'yearID': 2016,
 'stint': 1,
 'teamID': 'HOU',
 'lgID': 'AL',
 'G': 161,
 'AB': 640,
 'R': 108,
 'H': 216,
 '2B': 42,
 '3B': 5,
 'HR': 24,
 'RBI': 96.0,
 'SB': 30.0,
 'CS': 10.0,
 'BB': 60,
 'SO': 70.0,
 'IBB': 11.0,
 'HBP': 7.0,
 'SH': 3.0,
 'SF': 7.0,
 'GIDP': 15.0}

In [32]:
new_data_dict = {k: '' if isinstance(v, str) else np.nan for k, v in data_dict.items()}

In [34]:
new_data_dict

{'playerID': '',
 'yearID': nan,
 'stint': nan,
 'teamID': '',
 'lgID': '',
 'G': nan,
 'AB': nan,
 'R': nan,
 'H': nan,
 '2B': nan,
 '3B': nan,
 'HR': nan,
 'RBI': nan,
 'SB': nan,
 'CS': nan,
 'BB': nan,
 'SO': nan,
 'IBB': nan,
 'HBP': nan,
 'SH': nan,
 'SF': nan,
 'GIDP': nan}

In [36]:
random_data = []
for i in range(1000):
    d = dict()
    for k, v in data_dict.items():
        if isinstance(v, str):
            d[k] = np.random.choice(list('abcde'))
        else:
            d[k] = np.random.randint(10)
    random_data.append(pd.Series(d, name=i + len(bball_16)))

In [37]:
random_data

[playerID    d
 yearID      9
 stint       2
 teamID      b
 lgID        e
 G           9
 AB          1
 R           3
 H           3
 2B          3
 3B          3
 HR          1
 RBI         5
 SB          5
 CS          9
 BB          8
 SO          8
 IBB         5
 HBP         5
 SH          8
 SF          4
 GIDP        8
 Name: 16, dtype: object,
 playerID    e
 yearID      8
 stint       2
 teamID      a
 lgID        c
 G           8
 AB          2
 R           3
 H           5
 2B          4
 3B          7
 HR          4
 RBI         8
 SB          5
 CS          7
 BB          6
 SO          5
 IBB         5
 HBP         3
 SH          2
 SF          1
 GIDP        8
 Name: 17, dtype: object,
 playerID    c
 yearID      9
 stint       6
 teamID      c
 lgID        e
 G           0
 AB          0
 R           9
 H           6
 2B          7
 3B          8
 HR          6
 RBI         5
 SB          9
 CS          0
 BB          2
 SO          5
 IBB         2
 HBP         0
 SH          3
 SF          4
 GIDP        6
 Name: 18, dtype: object,
 playerID    d
 yearID      0
 stint       4
 teamID      c
 lgID        a
 G           2
 AB          8
 R           5
 H           4
 2B          2
 3B          4
 HR          8
 RBI         0
 SB          0
 CS          7
 BB          1
 SO          0
 IBB         2
 HBP         4
 SH          2
 SF          9
 GIDP        3
 Name: 19, dtype: object,
 playerID    e
 yearID      5
 stint       3
 teamID      a
 lgID        b
 G           9
 AB          0
 R           9
 H           6
 2B          5
 3B          1
 HR          7
 RBI         6
 SB          9
 CS          6
 BB          6
 SO          8
 IBB         0
 HBP         2
 SH          2
 SF          2
 GIDP        5
 Name: 20, dtype: object,
 playerID    b
 yearID      1
 stint       5
 teamID      e
 lgID        e
 G           2
 AB          7
 R           9
 H           9
 2B          8
 3B          6
 HR          5
 RBI         6
 SB          8
 CS          7
 BB          9
 SO          1
 IBB         5
 HBP         2
 SH          9
 SF          4
 GIDP        7
 Name: 21, dtype: object,
 playerID    a
 yearID      8
 stint       0
 teamID      a
 lgID        e
 G           4
 AB          8
 R           1
 H           7
 2B          8
 3B          5
 HR          5
 RBI         3
 SB          8
 CS          1
 BB          9
 SO          3
 IBB         9
 HBP         6
 SH          3
 SF          3
 GIDP        5
 Name: 22, dtype: object,
 playerID    c
 yearID      9
 stint       2
 teamID      b
 lgID        e
 G           5
 AB          3
 R           6
 H           1
 2B          4
 3B          1
 HR          7
 RBI         2
 SB          4
 CS          3
 BB          6
 SO          8
 IBB         4
 HBP         9
 SH          4
 SF          9
 GIDP        3
 Name: 23, dtype: object,
 playerID    a
 yearID      0
 stint       9
 teamID      e
 lgID        c
 G           1
 AB          0
 R           0
 H           6
 2B          9
 3B          5
 HR          9
 RBI         0
 SB          6
 CS          5
 BB          4
 SO          6
 IBB         4
 HBP         3
 SH          0
 SF          8
 GIDP        3
 Name: 24, dtype: object,
 playerID    b
 yearID      4
 stint       1
 teamID      b
 lgID        d
 G           8
 AB          9
 R           1
 H           8
 2B          0
 3B          0
 HR          7
 RBI         0
 SB          8
 CS          9
 BB          6
 SO          3
 IBB         4
 HBP         4
 SH          1
 SF          9
 GIDP        9
 Name: 25, dtype: object,
 playerID    d
 yearID      5
 stint       5
 teamID      d
 lgID        b
 G           3
 AB          9
 R           5
 H           4
 2B          5
 3B          6
 HR          8
 RBI         9
 SB          0
 CS          1
 BB          0
 SO          1
 IBB         2
 HBP         0
 SH          4
 SF          5
 GIDP        6
 Name: 26, dtype: object,
 playerID    a
 yearID      7
 stint       6
 teamID      a
 lgID        c
 G           7
 AB          2
 R           9
 H           8
 2B          8
 3B          3
 HR          8
 RBI         6
 SB          7
 CS          2
 BB          2
 SO          1
 IBB         0
 HBP         9
 SH          0
 SF          0
 GIDP        3
 Name: 27, dtype: object,
 playerID    c
 yearID      2
 stint       1
 teamID      e
 lgID        d
 G           1
 AB          9
 R           4
 H           1
 2B          4
 3B          9
 HR          8
 RBI         8
 SB          4
 CS          1
 BB          0
 SO          0
 IBB         0
 HBP         3
 SH          6
 SF          5
 GIDP        7
 Name: 28, dtype: object,
 playerID    e
 yearID      9
 stint       0
 teamID      a
 lgID        e
 G           2
 AB          7
 R           8
 H           7
 2B          2
 3B          0
 HR          5
 RBI         9
 SB          2
 CS          5
 BB          9
 SO          1
 IBB         7
 HBP         5
 SH          9
 SF          7
 GIDP        5
 Name: 29, dtype: object,
 playerID    c
 yearID      0
 stint       6
 teamID      d
 lgID        e
 G           4
 AB          0
 R           7
 H           1
 2B          2
 3B          1
 HR          9
 RBI         4
 SB          8
 CS          0
 BB          9
 SO          3
 IBB         3
 HBP         4
 SH          3
 SF          6
 GIDP        4
 Name: 30, dtype: object,
 playerID    d
 yearID      6
 stint       1
 teamID      b
 lgID        c
 G           1
 AB          3
 R           4
 H           7
 2B          3
 3B          9
 HR          5
 RBI         5
 SB          4
 CS          5
 BB          1
 SO          6
 IBB         1
 HBP         9
 SH          8
 SF          5
 GIDP        3
 Name: 31, dtype: object,
 playerID    c
 yearID      6
 stint       8
 teamID      b
 lgID        d
 G           9
 AB          3
 R           0
 H           6
 2B          3
 3B          5
 HR          2
 RBI         5
 SB          3
 CS          2
 BB          5
 SO          3
 IBB         6
 HBP         4
 SH          8
 SF          9
 GIDP        9
 Name: 32, dtype: object,
 playerID    b
 yearID      4
 stint       4
 teamID      e
 lgID        b
 G           0
 AB          3
 R           4
 H           3
 2B          8
 3B          9
 HR          0
 RBI         7
 SB          1
 CS          1
 BB          0
 SO          6
 IBB         0
 HBP         2
 SH          2
 SF          9
 GIDP        4
 Name: 33, dtype: object,
 playerID    a
 yearID      6
 stint       4
 teamID      d
 lgID        c
 G           0
 AB          4
 R           6
 H           0
 2B          7
 3B          6
 HR          9
 RBI         3
 SB          0
 CS          7
 BB          0
 SO          5
 IBB         9
 HBP         9
 SH          2
 SF          3
 GIDP        7
 Name: 34, dtype: object,
 playerID    d
 yearID      8
 stint       3
 teamID      e
 lgID        c
 G           1
 AB          3
 R           2
 H           2
 2B          2
 3B          2
 HR          5
 RBI         2
 SB          4
 CS          1
 BB          2
 SO          8
 IBB         6
 HBP         6
 SH          8
 SF          5
 GIDP        6
 Name: 35, dtype: object,
 playerID    c
 yearID      2
 stint       8
 teamID      a
 lgID        d
 G           4
 AB          1
 R           4
 H           3
 2B          8
 3B          1
 HR          9
 RBI         3
 SB          0
 CS          7
 BB          8
 SO          3
 IBB         3
 HBP         3
 SH          1
 SF          9
 GIDP        9
 Name: 36, dtype: object,
 playerID    b
 yearID      6
 stint       1
 teamID      d
 lgID        a
 G           3
 AB          4
 R           5
 H           7
 2B          6
 3B          0
 HR          8
 RBI         8
 SB          9
 CS          8
 BB          1
 SO          3
 IBB         3
 HBP         7
 SH          2
 SF          0
 GIDP        5
 Name: 37, dtype: object,
 playerID    e
 yearID      6
 stint       8
 teamID      b
 lgID        c
 G           4
 AB          7
 R           0
 H           3
 2B          6
 3B          7
 HR          9
 RBI         1
 SB          7
 CS          4
 BB          4
 SO          6
 IBB         3
 HBP         8
 SH          9
 SF          8
 GIDP        7
 Name: 38, dtype: object,
 playerID    d
 yearID      2
 stint       9
 teamID      a
 lgID        c
 G           7
 AB          2
 R           8
 H           5
 2B          3
 3B          5
 HR          3
 RBI         0
 SB          0
 CS          1
 BB          8
 SO          9
 IBB         6
 HBP         1
 SH          7
 SF          2
 GIDP        0
 Name: 39, dtype: object,
 playerID    e
 yearID      7
 stint       2
 teamID      a
 lgID        e
 G           7
 AB          0
 R           7
 H           0
 2B          5
 3B          3
 HR          5
 RBI         3
 SB          0
 CS          0
 BB          8
 SO          5
 IBB         3
 HBP         6
 SH          1
 SF          9
 GIDP        9
 Name: 40, dtype: object,
 playerID    c
 yearID      9
 stint       0
 teamID      e
 lgID        a
 G           5
 AB          6
 R           4
 H           3
 2B          8
 3B          0
 HR          0
 RBI         1
 SB          7
 CS          5
 BB          8
 SO          0
 IBB         7
 HBP         9
 SH          0
 SF          8
 GIDP        7
 Name: 41, dtype: object,
 playerID    a
 yearID      0
 stint       2
 teamID      c
 lgID        d
 G           6
 AB          0
 R           3
 H           3
 2B          1
 3B          5
 HR          2
 RBI         1
 SB          0
 CS          8
 BB          8
 SO          1
 IBB         1
 HBP         1
 SH          9
 SF          6
 GIDP        9
 Name: 42, dtype: object,
 playerID    c
 yearID      4
 stint       5
 teamID      c
 lgID        a
 G           6
 AB          6
 R           5
 H           2
 2B          7
 3B          1
 HR          6
 RBI         7
 SB          2
 CS          4
 BB          7
 SO          2
 IBB         1
 HBP         9
 SH          8
 SF          8
 GIDP        8
 Name: 43, dtype: object,
 playerID    d
 yearID      6
 stint       3
 teamID      d
 lgID        a
 G           1
 AB          6
 R           9
 H           1
 2B          0
 3B          0
 HR          7
 RBI         8
 SB          4
 CS          8
 BB          1
 SO          0
 IBB         2
 HBP         5
 SH          1
 SF          1
 GIDP        0
 Name: 44, dtype: object,
 playerID    b
 yearID      7
 stint       9
 teamID      e
 lgID        b
 G           3
 AB          8
 R           8
 H           0
 2B          5
 3B          2
 HR          8
 RBI         7
 SB          2
 CS          3
 BB          3
 SO          9
 IBB         9
 HBP         8
 SH          0
 SF          6
 GIDP        3
 Name: 45, dtype: object,
 playerID    e
 yearID      5
 stint       3
 teamID      e
 lgID        d
 G           4
 AB          3
 R           8
 H           6
 2B          8
 3B          6
 HR          5
 RBI         0
 SB          1
 CS          1
 BB          2
 SO          7
 IBB         5
 HBP         2
 SH          0
 SF          1
 GIDP        8
 Name: 46, dtype: object,
 playerID    e
 yearID      3
 stint       9
 teamID      b
 lgID        c
 G           7
 AB          8
 R           4
 H           4
 2B          2
 3B          2
 HR          4
 RBI         7
 SB          9
 CS          3
 BB          8
 SO          6
 IBB         6
 HBP         2
 SH          0
 SF          8
 GIDP        7
 Name: 47, dtype: object,
 playerID    c
 yearID      6
 stint       5
 teamID      d
 lgID        d
 G           6
 AB          3
 R           1
 H           0
 2B          8
 3B          5
 HR          2
 RBI         5
 SB          7
 CS          4
 BB          1
 SO          9
 IBB         4
 HBP         6
 SH          6
 SF          1
 GIDP        0
 Name: 48, dtype: object,
 playerID    b
 yearID      3
 stint       5
 teamID      d
 lgID        b
 G           4
 AB          5
 R           4
 H           2
 2B          8
 3B          6
 HR          1
 RBI         0
 SB          1
 CS          7
 BB          6
 SO          0
 IBB         5
 HBP         9
 SH          1
 SF          5
 GIDP        6
 Name: 49, dtype: object,
 playerID    e
 yearID      5
 stint       5
 teamID      c
 lgID        e
 G           9
 AB          4
 R           4
 H           2
 2B          6
 3B          9
 HR          3
 RBI         7
 SB          0
 CS          6
 BB          3
 SO          9
 IBB         5
 HBP         3
 SH          3
 SF          1
 GIDP        7
 Name: 50, dtype: object,
 playerID    e
 yearID      5
 stint       4
 teamID      c
 lgID        d
 G           2
 AB          3
 R           1
 H           2
 2B          0
 3B          3
 HR          6
 RBI         1
 SB          1
 CS          3
 BB          8
 SO          6
 IBB         1
 HBP         0
 SH          8
 SF          5
 GIDP        1
 Name: 51, dtype: object,
 playerID    d
 yearID      0
 stint       9
 teamID      d
 lgID        b
 G           1
 AB          4
 R           0
 H           8
 2B          2
 3B          3
 HR          8
 RBI         2
 SB          1
 CS          7
 BB          6
 SO          2
 IBB         4
 HBP         8
 SH          3
 SF          6
 GIDP        0
 Name: 52, dtype: object,
 playerID    e
 yearID      4
 stint       9
 teamID      e
 lgID        e
 G           9
 AB          0
 R           5
 H           8
 2B          1
 3B          6
 HR          3
 RBI         2
 SB          8
 CS          7
 BB          2
 SO          3
 IBB         5
 HBP         5
 SH          9
 SF          1
 GIDP        7
 Name: 53, dtype: object,
 playerID    d
 yearID      8
 stint       4
 teamID      d
 lgID        e
 G           4
 AB          8
 R           1
 H           7
 2B          7
 3B          1
 HR          7
 RBI         8
 SB          9
 CS          6
 BB          3
 SO          9
 IBB         4
 HBP         2
 SH          4
 SF          0
 GIDP        7
 Name: 54, dtype: object,
 playerID    d
 yearID      2
 stint       2
 teamID      c
 lgID        d
 G           9
 AB          3
 R           7
 H           9
 2B          6
 3B          3
 HR          2
 RBI         5
 SB          7
 CS          7
 BB          3
 SO          7
 IBB         4
 HBP         7
 SH          3
 SF          8
 GIDP        2
 Name: 55, dtype: object,
 playerID    c
 yearID      1
 stint       1
 teamID      e
 lgID        b
 G           6
 AB          0
 R           0
 H           0
 2B          7
 3B          0
 HR          4
 RBI         2
 SB          1
 CS          2
 BB          7
 SO          1
 IBB         9
 HBP         8
 SH          4
 SF          9
 GIDP        0
 Name: 56, dtype: object,
 playerID    a
 yearID      2
 stint       0
 teamID      d
 lgID        e
 G           6
 AB          1
 R           6
 H           7
 2B          9
 3B          4
 HR          8
 RBI         5
 SB          9
 CS          6
 BB          2
 SO          1
 IBB         1
 HBP         3
 SH          4
 SF          9
 GIDP        2
 Name: 57, dtype: object,
 playerID    b
 yearID      1
 stint       6
 teamID      c
 lgID        b
 G           0
 AB          8
 R           2
 H           7
 2B          9
 3B          8
 HR          0
 RBI         3
 SB          3
 CS          0
 BB          1
 SO          1
 IBB         7
 HBP         0
 SH          8
 SF          3
 GIDP        7
 Name: 58, dtype: object,
 playerID    a
 yearID      9
 stint       7
 teamID      c
 lgID        c
 G           2
 AB          1
 R           9
 H           6
 2B          6
 3B          0
 HR          5
 RBI         6
 SB          1
 CS          7
 BB          0
 SO          9
 IBB         5
 HBP         5
 SH          4
 SF          7
 GIDP        1
 Name: 59, dtype: object,
 playerID    b
 yearID      6
 stint       9
 teamID      b
 lgID        c
 G           1
 AB          1
 R           0
 H           5
 2B          0
 3B          6
 HR          0
 RBI         8
 SB          1
 CS          5
 BB          2
 SO          3
 IBB         4
 HBP         0
 SH          4
 SF          9
 GIDP        2
 Name: 60, dtype: object,
 playerID    e
 yearID      8
 stint       7
 teamID      d
 lgID        e
 G           9
 AB          3
 R           1
 H           8
 2B          5
 3B          9
 HR          7
 RBI         4
 SB          9
 CS          9
 BB          7
 SO          6
 IBB         3
 HBP         4
 SH          4
 SF          1
 GIDP        1
 Name: 61, dtype: object,
 playerID    a
 yearID      5
 stint       9
 teamID      c
 lgID        e
 G           8
 AB          8
 R           6
 H           4
 2B          1
 3B          5
 HR          2
 RBI         6
 SB          7
 CS          8
 BB          3
 SO          4
 IBB         3
 HBP         4
 SH          8
 SF          9
 GIDP        9
 Name: 62, dtype: object,
 playerID    d
 yearID      6
 stint       8
 teamID      b
 lgID        a
 G           3
 AB          2
 R           7
 H           2
 2B          9
 3B          7
 HR          9
 RBI         6
 SB          2
 CS          6
 BB          0
 SO          1
 IBB         9
 HBP         6
 SH          8
 SF          9
 GIDP        8
 Name: 63, dtype: object,
 playerID    e
 yearID      8
 stint       1
 teamID      b
 lgID        d
 G           4
 AB          4
 R           7
 H           8
 2B          2
 3B          9
 HR          2
 RBI         0
 SB          7
 CS          7
 BB          0
 SO          5
 IBB         8
 HBP         2
 SH          1
 SF          1
 GIDP        7
 Name: 64, dtype: object,
 playerID    c
 yearID      6
 stint       8
 teamID      a
 lgID        e
 G           1
 AB          3
 R           4
 H           0
 2B          4
 3B          6
 HR          6
 RBI         1
 SB          3
 CS          0
 BB          8
 SO          3
 IBB         0
 HBP         9
 SH          1
 SF          9
 GIDP        3
 Name: 65, dtype: object,
 playerID    d
 yearID      6
 stint       7
 teamID      b
 lgID        b
 G           0
 AB          6
 R           6
 H           8
 2B          7
 3B          9
 HR          6
 RBI         9
 SB          0
 CS          7
 BB          9
 SO          1
 IBB         3
 HBP         2
 SH          8
 SF          9
 GIDP        9
 Name: 66, dtype: object,
 playerID    d
 yearID      6
 stint       9
 teamID      b
 lgID        d
 G           4
 AB          9
 R           9
 H           5
 2B          2
 3B          9
 HR          6
 RBI         0
 SB          2
 CS          4
 BB          3
 SO          3
 IBB         2
 HBP         1
 SH          5
 SF          3
 GIDP        8
 Name: 67, dtype: object,
 playerID    a
 yearID      2
 stint       2
 teamID      b
 lgID        c
 G           6
 AB          1
 R           4
 H           8
 2B          1
 3B          5
 HR          1
 RBI         5
 SB          2
 CS          2
 BB          9
 SO          5
 IBB         9
 HBP         0
 SH          3
 SF          1
 GIDP        8
 Name: 68, dtype: object,
 playerID    c
 yearID      1
 stint       0
 teamID      b
 lgID        b
 G           1
 AB          4
 R           0
 H           7
 2B          3
 3B          4
 HR          5
 RBI         4
 SB          8
 CS          3
 BB          7
 SO          1
 IBB         9
 HBP         5
 SH          8
 SF          2
 GIDP        6
 Name: 69, dtype: object,
 playerID    a
 yearID      1
 stint       0
 teamID      a
 lgID        e
 G           3
 AB          0
 R           8
 H           3
 2B          3
 3B          8
 HR          7
 RBI         0
 SB          9
 CS          5
 BB          5
 SO          6
 IBB         8
 HBP         5
 SH          2
 SF          5
 GIDP        3
 Name: 70, dtype: object,
 playerID    c
 yearID      4
 stint       0
 teamID      a
 lgID        a
 G           3
 AB          0
 R           9
 H           6
 2B          0
 3B          3
 HR          7
 RBI         4
 SB          6
 CS          2
 BB          5
 SO          1
 IBB         4
 HBP         4
 SH          4
 SF          6
 GIDP        3
 Name: 71, dtype: object,
 playerID    c
 yearID      6
 stint       4
 teamID      a

In [38]:
%%timeit
bball_16_copy = bball_16.copy()
bball_16_copy = bball_16_copy.append(random_data)

<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

24.2 ms ± 207 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<magic-timeit>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

여러 DataFrame 을 함께 연결

In [40]:
stocks_2016 = pd.read_csv('data/stocks_2016.csv', index_col='Symbol')
stocks_2017 = pd.read_csv('data/stocks_2017.csv', index_col='Symbol')

In [41]:
stocks_2016

        Shares  Low  High
Symbol
AAPL        80   95   110
TSLA        50   80   130
WMT         40   55    70

In [42]:
s_list = [stocks_2016, stocks_2017]
s_list

[        Shares  Low  High
 Symbol
 AAPL        80   95   110
 TSLA        50   80   130
 WMT         40   55    70,
         Shares  Low  High
 Symbol
 AAPL        50  120   140
 GE         100   30    40
 IBM         87   75    95
 SLB         20   55    85
 TXN        500   15    23
 TSLA       100  100   300]

In [43]:
pd.concat(s_list)

        Shares  Low  High
Symbol
AAPL        80   95   110
TSLA        50   80   130
WMT         40   55    70
AAPL        50  120   140
GE         100   30    40
IBM         87   75    95
SLB         20   55    85
TXN        500   15    23
TSLA       100  100   300

In [44]:
pd.concat(s_list,
          keys=['2016', '2017'],
          names=['Year', 'Symbol'])

             Shares  Low  High
Year Symbol
2016 AAPL        80   95   110
     TSLA        50   80   130
     WMT         40   55    70
2017 AAPL        50  120   140
     GE         100   30    40
     IBM         87   75    95
     SLB         20   55    85
     TXN        500   15    23
     TSLA       100  100   300

In [47]:
pd.concat(s_list,
          keys=['2016', '2017'],
          axis='columns',
          names=['Year', None])

Year     2016                2017
       Shares   Low   High Shares    Low   High
Symbol
AAPL     80.0  95.0  110.0   50.0  120.0  140.0
TSLA     50.0  80.0  130.0  100.0  100.0  300.0
WMT      40.0  55.0   70.0    NaN    NaN    NaN
GE        NaN   NaN    NaN  100.0   30.0   40.0
IBM       NaN   NaN    NaN   87.0   75.0   95.0
SLB       NaN   NaN    NaN   20.0   55.0   85.0
TXN       NaN   NaN    NaN  500.0   15.0   23.0

In [48]:
pd.concat(s_list,
          keys=['2016', '2017'],
          join='inner',
          axis='columns',
          names=['Year', None])

Year     2016            2017
       Shares Low High Shares  Low High
Symbol
AAPL       80  95  110     50  120  140
TSLA       50  80  130    100  100  300

concat, join, merge 차이점 이해

In [49]:
years = 2016, 2017, 2018

In [50]:
stock_tables = [pd.read_csv(f'data/stocks_{year}.csv', index_col='Symbol') for year in years]

In [51]:
stocks_2016, stocks_2017, stocks_2018 = stock_tables

In [56]:
stock_tables

[        Shares  Low  High
 Symbol
 AAPL        80   95   110
 TSLA        50   80   130
 WMT         40   55    70,
         Shares  Low  High
 Symbol
 AAPL        50  120   140
 GE         100   30    40
 IBM         87   75    95
 SLB         20   55    85
 TXN        500   15    23
 TSLA       100  100   300,
         Shares  Low  High
 Symbol
 AAPL        40  135   170
 AMZN         8  900  1125
 TSLA        50  220   400]

In [52]:
stocks_2016

        Shares  Low  High
Symbol
AAPL        80   95   110
TSLA        50   80   130
WMT         40   55    70

In [53]:
stocks_2017

        Shares  Low  High
Symbol
AAPL        50  120   140
GE         100   30    40
IBM         87   75    95
SLB         20   55    85
TXN        500   15    23
TSLA       100  100   300

In [54]:
stocks_2018

        Shares  Low  High
Symbol
AAPL        40  135   170
AMZN         8  900  1125
TSLA        50  220   400

In [55]:
pd.concat(stock_tables, keys=[2016, 2017, 2018])

             Shares  Low  High
     Symbol
2016 AAPL        80   95   110
     TSLA        50   80   130
     WMT         40   55    70
2017 AAPL        50  120   140
     GE         100   30    40
     IBM         87   75    95
     SLB         20   55    85
     TXN        500   15    23
     TSLA       100  100   300
2018 AAPL        40  135   170
     AMZN         8  900  1125
     TSLA        50  220   400

In [57]:
pd.concat(dict(zip(years, stock_tables)), axis='columns')

         2016                2017                 2018
       Shares   Low   High Shares    Low   High Shares    Low    High
Symbol
AAPL     80.0  95.0  110.0   50.0  120.0  140.0   40.0  135.0   170.0
TSLA     50.0  80.0  130.0  100.0  100.0  300.0   50.0  220.0   400.0
WMT      40.0  55.0   70.0    NaN    NaN    NaN    NaN    NaN     NaN
GE        NaN   NaN    NaN  100.0   30.0   40.0    NaN    NaN     NaN
IBM       NaN   NaN    NaN   87.0   75.0   95.0    NaN    NaN     NaN
SLB       NaN   NaN    NaN   20.0   55.0   85.0    NaN    NaN     NaN
TXN       NaN   NaN    NaN  500.0   15.0   23.0    NaN    NaN     NaN
AMZN      NaN   NaN    NaN    NaN    NaN    NaN    8.0  900.0  1125.0

In [66]:
list(zip(years, stock_tables))

[(2016,
          Shares  Low  High
  Symbol
  AAPL        80   95   110
  TSLA        50   80   130
  WMT         40   55    70),
 (2017,
          Shares  Low  High
  Symbol
  AAPL        50  120   140
  GE         100   30    40
  IBM         87   75    95
  SLB         20   55    85
  TXN        500   15    23
  TSLA       100  100   300),
 (2018,
          Shares  Low  High
  Symbol
  AAPL        40  135   170
  AMZN         8  900  1125
  TSLA        50  220   400)]

In [67]:
stocks_2016.join(
    stocks_2017,
    lsuffix='_2016',
    rsuffix='_2017',
    how='outer'
)

        Shares_2016  Low_2016  High_2016  Shares_2017  Low_2017  High_2017
Symbol
AAPL           80.0      95.0      110.0         50.0     120.0      140.0
GE              NaN       NaN        NaN        100.0      30.0       40.0
IBM             NaN       NaN        NaN         87.0      75.0       95.0
SLB             NaN       NaN        NaN         20.0      55.0       85.0
TSLA           50.0      80.0      130.0        100.0     100.0      300.0
TXN             NaN       NaN        NaN        500.0      15.0       23.0
WMT            40.0      55.0       70.0          NaN       NaN        NaN

In [70]:
other = [stocks_2017.add_suffix('_2017'),
         stocks_2018.add_suffix('_2018')]
other

[        Shares_2017  Low_2017  High_2017
 Symbol
 AAPL             50       120        140
 GE              100        30         40
 IBM              87        75         95
 SLB              20        55         85
 TXN             500        15         23
 TSLA            100       100        300,
         Shares_2018  Low_2018  High_2018
 Symbol
 AAPL             40       135        170
 AMZN              8       900       1125
 TSLA             50       220        400]

In [69]:
stocks_2016.add_suffix('_2016').join(other, how='outer')

,Shares_2016,Low_2016,High_2016,Shares_2017,Low_2017,High_2017,Shares_2018,Low_2018,High_2018
Symbol,,,,,,,,,
AAPL,80.0,95.0,110.0,50.0,120.0,140.0,40.0,135.0,170.0
TSLA,50.0,80.0,130.0,100.0,100.0,300.0,50.0,220.0,400.0
WMT,40.0,55.0,70.0,NaN,NaN,NaN,NaN,NaN,NaN
GE,NaN,NaN,NaN,100.0,30.0,40.0,NaN,NaN,NaN
IBM,NaN,NaN,NaN,87.0,75.0,95.0,NaN,NaN,NaN
SLB,NaN,NaN,NaN,20.0,55.0,85.0,NaN,NaN,NaN
TXN,NaN,NaN,NaN,500.0,15.0,23.0,NaN,NaN,NaN
AMZN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,900.0,1125.0

In [71]:
stock_join = stocks_2016.add_suffix('_2016').join(other, how='outer')

In [76]:
stock_concat = (
    pd.concat(
        dict(zip(years, stock_tables)), axis='columns'
    )
    .swaplevel(axis=1)
    .pipe(lambda df_: df_.set_axis(df_.columns.to_flat_index(), axis=1))
    .rename(lambda label: '_'.join([str(x) for x in label]), axis=1)
)
stock_concat

,Shares_2016,Low_2016,High_2016,Shares_2017,Low_2017,High_2017,Shares_2018,Low_2018,High_2018
Symbol,,,,,,,,,
AAPL,80.0,95.0,110.0,50.0,120.0,140.0,40.0,135.0,170.0
TSLA,50.0,80.0,130.0,100.0,100.0,300.0,50.0,220.0,400.0
WMT,40.0,55.0,70.0,NaN,NaN,NaN,NaN,NaN,NaN
GE,NaN,NaN,NaN,100.0,30.0,40.0,NaN,NaN,NaN
IBM,NaN,NaN,NaN,87.0,75.0,95.0,NaN,NaN,NaN
SLB,NaN,NaN,NaN,20.0,55.0,85.0,NaN,NaN,NaN
TXN,NaN,NaN,NaN,500.0,15.0,23.0,NaN,NaN,NaN
AMZN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,900.0,1125.0

In [77]:
stock_join.equals(stock_concat)

True

In [81]:
stocks_2016.merge(stocks_2017,
                  left_index=True,
                  right_index=True
                  )

        Shares_x  Low_x  High_x  Shares_y  Low_y  High_y
Symbol
AAPL          80     95     110        50    120     140
TSLA          50     80     130       100    100     300

In [82]:
stock_merge = (
    stocks_2016
    .merge(
        stocks_2017,
        left_index=True,
        right_index=True,
        how='outer',
        suffixes=('_2016', '_2017')
    )
    .merge(
        stocks_2018.add_suffix('_2018'),
        left_index=True,
        right_index=True,
        how='outer'
    )
)
stock_merge

,Shares_2016,Low_2016,High_2016,Shares_2017,Low_2017,High_2017,Shares_2018,Low_2018,High_2018
Symbol,,,,,,,,,
AAPL,80.0,95.0,110.0,50.0,120.0,140.0,40.0,135.0,170.0
AMZN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,900.0,1125.0
GE,NaN,NaN,NaN,100.0,30.0,40.0,NaN,NaN,NaN
IBM,NaN,NaN,NaN,87.0,75.0,95.0,NaN,NaN,NaN
SLB,NaN,NaN,NaN,20.0,55.0,85.0,NaN,NaN,NaN
TSLA,50.0,80.0,130.0,100.0,100.0,300.0,50.0,220.0,400.0
TXN,NaN,NaN,NaN,500.0,15.0,23.0,NaN,NaN,NaN
WMT,40.0,55.0,70.0,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
stock_concat.sort_index().equals(stock_merge)

True

In [84]:
names = ['prices', 'transactions']

In [85]:
food_tables = [pd.read_csv('data/food_{}.csv'.format(name)) for name in names]
food_tables

[     item store  price  Date
 0    pear     A   0.99  2017
 1    pear     B   1.99  2017
 2   peach     A   2.99  2017
 3   peach     B   3.49  2017
 4  banana     A   0.39  2017
 5  banana     B   0.49  2017
 6   steak     A   5.99  2017
 7   steak     B   6.99  2017
 8   steak     B   4.99  2015,
    custid     item store  quantity
 0       1     pear     A         5
 1       1   banana     A        10
 2       2    steak     B         3
 3       2     pear     B         1
 4       2    peach     B         2
 5       2    steak     B         1
 6       2  coconut     B         4]

In [86]:
food_prices, food_transactions = food_tables

In [87]:
food_prices

     item store  price  Date
0    pear     A   0.99  2017
1    pear     B   1.99  2017
2   peach     A   2.99  2017
3   peach     B   3.49  2017
4  banana     A   0.39  2017
5  banana     B   0.49  2017
6   steak     A   5.99  2017
7   steak     B   6.99  2017
8   steak     B   4.99  2015

In [88]:
food_transactions

   custid     item store  quantity
0       1     pear     A         5
1       1   banana     A        10
2       2    steak     B         3
3       2     pear     B         1
4       2    peach     B         2
5       2    steak     B         1
6       2  coconut     B         4

In [89]:
food_transactions.merge(food_prices, on=['item', 'store'])

   custid    item store  quantity  price  Date
0       1    pear     A         5   0.99  2017
1       1  banana     A        10   0.39  2017
2       2   steak     B         3   6.99  2017
3       2   steak     B         3   4.99  2015
4       2   steak     B         1   6.99  2017
5       2   steak     B         1   4.99  2015
6       2    pear     B         1   1.99  2017
7       2   peach     B         2   3.49  2017

In [90]:
food_transactions.merge(food_prices.query('Date == 2017'), how='left')

   custid     item store  quantity  price    Date
0       1     pear     A         5   0.99  2017.0
1       1   banana     A        10   0.39  2017.0
2       2    steak     B         3   6.99  2017.0
3       2     pear     B         1   1.99  2017.0
4       2    peach     B         2   3.49  2017.0
5       2    steak     B         1   6.99  2017.0
6       2  coconut     B         4    NaN     NaN

In [94]:
food_prices.query('Date == 2017')

     item store  price  Date
0    pear     A   0.99  2017
1    pear     B   1.99  2017
2   peach     A   2.99  2017
3   peach     B   3.49  2017
4  banana     A   0.39  2017
5  banana     B   0.49  2017
6   steak     A   5.99  2017
7   steak     B   6.99  2017

In [93]:
food_prices_join = food_prices.query('Date == 2017').set_index(['item', 'store'])
food_prices_join

              price  Date
item   store
pear   A       0.99  2017
       B       1.99  2017
peach  A       2.99  2017
       B       3.49  2017
banana A       0.39  2017
       B       0.49  2017
steak  A       5.99  2017
       B       6.99  2017

In [95]:
food_transactions.join(food_prices_join, on=['item', 'store'])

   custid     item store  quantity  price    Date
0       1     pear     A         5   0.99  2017.0
1       1   banana     A        10   0.39  2017.0
2       2    steak     B         3   6.99  2017.0
3       2     pear     B         1   1.99  2017.0
4       2    peach     B         2   3.49  2017.0
5       2    steak     B         1   6.99  2017.0
6       2  coconut     B         4    NaN     NaN

In [1]:
import glob
import pandas as pd
import numpy as np

In [2]:
df_list = []

In [3]:
for filename in glob.glob('data/gas prices/*.csv'):
    df_list.append(pd.read_csv(filename, index_col='Week', parse_dates=['Week']))

In [4]:
gas = pd.concat(df_list, axis='columns')

In [5]:
gas

            Midgrade  Premium  Diesel  All Grades  Regular
Week
2017-09-25     2.859    3.105   2.788       2.701    2.583
2017-09-18     2.906    3.151   2.791       2.750    2.634
2017-09-11     2.953    3.197   2.802       2.800    2.685
2017-09-04     2.946    3.191   2.758       2.794    2.679
2017-08-28     2.668    2.901   2.605       2.513    2.399
...              ...      ...     ...         ...      ...
2007-01-29     2.277    2.381   2.413       2.213    2.165
2007-01-22     2.285    2.391   2.430       2.216    2.165
2007-01-15     2.347    2.453   2.463       2.280    2.229
2007-01-08     2.418    2.523   2.537       2.354    2.306
2007-01-01     2.442    2.547   2.580       2.382    2.334

[561 rows x 5 columns]

SQL 데이터베이스에 연결

In [6]:
from sqlalchemy import create_engine

In [7]:
engine = create_engine('sqlite:///data/chinook.db')

In [8]:
tracks = pd.read_sql_table('tracks', engine)
tracks

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
...,...,...,...,...,...,...,...,...,...
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,2,24,None,286741,4718950,0.99
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,Franz Schubert,139200,2283131,0.99
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,2,24,Claudio Monteverdi,66639,1189062,0.99
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99
3502,3503,Koyaanisqatsi,347,2,10,Philip Glass,206005,3305164,0.99

In [11]:
(
    pd.read_sql_table('genres', engine)
    .merge(tracks[['GenreId', 'Milliseconds']],
           on='GenreId',
           how='left')
    .drop('GenreId', axis='columns')
)

           Name  Milliseconds
0          Rock        343719
1          Rock        342562
2          Rock        230619
3          Rock        252051
4          Rock        375418
...         ...           ...
3498  Classical        286741
3499  Classical        139200
3500  Classical         66639
3501  Classical        221331
3502      Opera        174813

[3503 rows x 2 columns]

In [20]:
(
    pd.read_sql_table('genres', engine)
    .merge(tracks[['GenreId', 'Milliseconds']],
           on='GenreId',
           how='left')
    .drop('GenreId', axis='columns')
    .groupby('Name')
    ['Milliseconds']
    .mean()
    .pipe(lambda s_: pd.to_timedelta(s_, unit='ms').rename('Length'))
    .dt.floor('s')
    .sort_values()
)

Name
Rock And Roll        0 days 00:02:14
Opera                0 days 00:02:54
Hip Hop/Rap          0 days 00:02:58
Easy Listening       0 days 00:03:09
Bossa Nova           0 days 00:03:39
R&B/Soul             0 days 00:03:40
World                0 days 00:03:44
Pop                  0 days 00:03:49
Latin                0 days 00:03:52
Alternative & Punk   0 days 00:03:54
Soundtrack           0 days 00:04:04
Reggae               0 days 00:04:07
Alternative          0 days 00:04:24
Blues                0 days 00:04:30
Rock                 0 days 00:04:43
Jazz                 0 days 00:04:51
Classical            0 days 00:04:53
Heavy Metal          0 days 00:04:57
Electronica/Dance    0 days 00:05:02
Metal                0 days 00:05:09
Comedy               0 days 00:26:25
TV Shows             0 days 00:35:45
Drama                0 days 00:42:55
Science Fiction      0 days 00:43:45
Sci Fi & Fantasy     0 days 00:48:31
Name: Length, dtype: timedelta64[ns]

In [21]:
cust = pd.read_sql_table('customers', engine, columns=['CustomerId', 'FirstName', 'LastName'])

In [22]:
invoice = pd.read_sql_table('invoices', engine, columns=['InvoiceId', 'CustomerId'])

In [23]:
invoice_items = pd.read_sql_table('invoice_items', engine, columns=['InvoiceId', 'UnitPrice', 'Quantity'])

In [27]:
(
    cust
    .merge(invoice, on='CustomerId')
    .merge(invoice_items, on='InvoiceId')
)

      CustomerId FirstName    LastName  InvoiceId  UnitPrice  Quantity
0              1      Luís   Gonçalves         98       1.99         1
1              1      Luís   Gonçalves         98       1.99         1
2              1      Luís   Gonçalves        121       0.99         1
3              1      Luís   Gonçalves        121       0.99         1
4              1      Luís   Gonçalves        121       0.99         1
...          ...       ...         ...        ...        ...       ...
2235          59      Puja  Srivastava        284       0.99         1
2236          59      Puja  Srivastava        284       0.99         1
2237          59      Puja  Srivastava        284       0.99         1
2238          59      Puja  Srivastava        284       0.99         1
2239          59      Puja  Srivastava        284       0.99         1

[2240 rows x 6 columns]

In [31]:
(
    cust
    .merge(invoice, on='CustomerId')
    .merge(invoice_items, on='InvoiceId')
    .assign(Total=lambda df_: df_.Quantity * df_.UnitPrice)
    .groupby(['CustomerId', 'FirstName', 'LastName'])
    ['Total']
    .sum()
    .sort_values(ascending=False)
)

CustomerId  FirstName  LastName
6           Helena     Holý            49.62
26          Richard    Cunningham      47.62
57          Luis       Rojas           46.62
45          Ladislav   Kovács          45.62
46          Hugh       O'Reilly        45.62
37          Fynn       Zimmermann      43.62
24          Frank      Ralston         43.62
28          Julia      Barnett         43.62
25          Victor     Stevens         42.62
7           Astrid     Gruber          42.62
44          Terhi      Hämäläinen      41.62
43          Isabelle   Mercier         40.62
5           František  Wichterlová     40.62
48          Johannes   Van der Berg    40.62
20          Dan        Miller          39.62
42          Wyatt      Girard          39.62
34          João       Fernandes       39.62
22          Heather    Leacock         39.62
1           Luís       Gonçalves       39.62
17          Jack       Smith           39.62
3           François   Tremblay        39.62
4           Bjørn      Hansen          39.62
39          Camille    Bernard         38.62
58          Manoj      Pareek          38.62
40          Dominique  Lefebvre        38.62
19          Tim        Goyer           38.62
15          Jennifer   Peterson        38.62
51          Joakim     Johansson       38.62
47          Lucas      Mancini         37.62
53          Phil       Hughes          37.62
49          Stanisław  Wójcik          37.62
55          Mark       Taylor          37.62
56          Diego      Gutiérrez       37.62
52          Emma       Jones           37.62
41          Marc       Dubois          37.62
50          Enrique    Muñoz           37.62
54          Steve      Murray          37.62
30          Edward     Francis         37.62
38          Niklas     Schröder        37.62
18          Michelle   Brooks          37.62
8           Daan       Peeters         37.62
9           Kara       Nielsen         37.62
10          Eduardo    Martins         37.62
11          Alexandre  Rocha           37.62
12          Roberto    Almeida         37.62
13          Fernanda   Ramos           37.62
14          Mark       Philips         37.62
16          Frank      Harris          37.62
21          Kathy      Chase           37.62
36          Hannah     Schneider       37.62
23          John       Gordon          37.62
27          Patrick    Gray            37.62
29          Robert     Brown           37.62
2           Leonie     Köhler          37.62
31          Martha     Silk            37.62
32          Aaron      Mitchell        37.62
33          Ellie      Sullivan        37.62
35          Madalena   Sampaio         37.62
59          Puja       Srivastava      36.64
Name: Total, dtype: float64